#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : R-slider
Version  : 0.3.0
Release  : 22
URL      : https://cran.r-project.org/src/contrib/slider_0.3.0.tar.gz
Source0  : https://cran.r-project.org/src/contrib/slider_0.3.0.tar.gz
Summary  : Sliding Window Functions
Group    : Development/Tools
License  : MIT
Requires: R-slider-lib = %{version}-%{release}
Requires: R-cli
Requires: R-rlang
Requires: R-vctrs
Requires: R-warp
BuildRequires : R-cli
BuildRequires : R-rlang
BuildRequires : R-vctrs
BuildRequires : R-warp
BuildRequires : buildreq-R

%description
type. Cumulative and expanding windows are also supported. For more
    advanced usage, an index can be used as a secondary vector that
    defines how sliding windows are to be created.

%package lib
Summary: lib components for the R-slider package.
Group: Libraries

%description lib
lib components for the R-slider package.


%prep
%setup -q -n slider
cd %{_builddir}/slider

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1668649474

%install
export SOURCE_DATE_EPOCH=1668649474
rm -rf %{buildroot}
export LANG=C.UTF-8
export CFLAGS="$CFLAGS -O3 -flto -fno-semantic-interposition "
export FCFLAGS="$FFLAGS -O3 -flto -fno-semantic-interposition "
export FFLAGS="$FFLAGS -O3 -flto -fno-semantic-interposition "
export CXXFLAGS="$CXXFLAGS -O3 -flto -fno-semantic-interposition "
export AR=gcc-ar
export RANLIB=gcc-ranlib
export LDFLAGS="$LDFLAGS  -Wl,-z -Wl,relro"
mkdir -p %{buildroot}/usr/lib64/R/library

mkdir -p ~/.R
mkdir -p ~/.stash
echo "CFLAGS = $CFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper" > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
R CMD INSTALL --install-tests --use-LTO --built-timestamp=${SOURCE_DATE_EPOCH} --data-compress=none --compress=none --build  -l %{buildroot}/usr/lib64/R/library .
for i in `find %{buildroot}/usr/lib64/R/ -name "*.so"`; do mv $i $i.avx2 ; mv $i.avx2 ~/.stash/; done
echo "CFLAGS = $CFLAGS -march=x86-64-v4 -ftree-vectorize  -mno-vzeroupper -mprefer-vector-width=512 " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=x86-64-v4 -ftree-vectorize  -mno-vzeroupper -mprefer-vector-width=512 " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=x86-64-v4 -ftree-vectorize -mno-vzeroupper -mprefer-vector-width=512  " >> ~/.R/Makevars
R CMD INSTALL --preclean --install-tests --use-LTO --no-test-load --data-compress=none --compress=none --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}/usr/lib64/R/library .
for i in `find %{buildroot}/usr/lib64/R/ -name "*.so"`; do mv $i $i.avx512 ; mv $i.avx512 ~/.stash/; done
echo "CFLAGS = $CFLAGS -ftree-vectorize " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -ftree-vectorize " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -ftree-vectorize " >> ~/.R/Makevars
R CMD INSTALL --preclean --use-LTO --install-tests --data-compress=none --compress=none --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}/usr/lib64/R/library .
cp ~/.stash/* %{buildroot}/usr/lib64/R/library/*/libs/ || :
%{__rm} -rf %{buildroot}%{_datadir}/R/library/R.css
%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export _R_CHECK_FORCE_SUGGESTS_=false
R CMD check --no-manual --no-examples --no-codoc . || :


%files
%defattr(-,root,root,-)
/usr/lib64/R/library/slider/DESCRIPTION
/usr/lib64/R/library/slider/INDEX
/usr/lib64/R/library/slider/LICENSE
/usr/lib64/R/library/slider/Meta/Rd.rds
/usr/lib64/R/library/slider/Meta/features.rds
/usr/lib64/R/library/slider/Meta/hsearch.rds
/usr/lib64/R/library/slider/Meta/links.rds
/usr/lib64/R/library/slider/Meta/nsInfo.rds
/usr/lib64/R/library/slider/Meta/package.rds
/usr/lib64/R/library/slider/Meta/vignette.rds
/usr/lib64/R/library/slider/NAMESPACE
/usr/lib64/R/library/slider/NEWS.md
/usr/lib64/R/library/slider/R/slider
/usr/lib64/R/library/slider/R/slider.rdb
/usr/lib64/R/library/slider/R/slider.rdx
/usr/lib64/R/library/slider/doc/index.html
/usr/lib64/R/library/slider/doc/rowwise.R
/usr/lib64/R/library/slider/doc/rowwise.Rmd
/usr/lib64/R/library/slider/doc/rowwise.html
/usr/lib64/R/library/slider/doc/slider.R
/usr/lib64/R/library/slider/doc/slider.Rmd
/usr/lib64/R/library/slider/doc/slider.html
/usr/lib64/R/library/slider/doc/tsibble.R
/usr/lib64/R/library/slider/doc/tsibble.Rmd
/usr/lib64/R/library/slider/doc/tsibble.html
/usr/lib64/R/library/slider/help/AnIndex
/usr/lib64/R/library/slider/help/aliases.rds
/usr/lib64/R/library/slider/help/paths.rds
/usr/lib64/R/library/slider/help/slider.rdb
/usr/lib64/R/library/slider/help/slider.rdx
/usr/lib64/R/library/slider/html/00Index.html
/usr/lib64/R/library/slider/html/R.css
/usr/lib64/R/library/slider/tests/testthat.R
/usr/lib64/R/library/slider/tests/testthat/_snaps/block.md
/usr/lib64/R/library/slider/tests/testthat/_snaps/conditions.md
/usr/lib64/R/library/slider/tests/testthat/_snaps/hop-index-vec.md
/usr/lib64/R/library/slider/tests/testthat/_snaps/hop-index.md
/usr/lib64/R/library/slider/tests/testthat/_snaps/hop-index2-vec.md
/usr/lib64/R/library/slider/tests/testthat/_snaps/hop-index2.md
/usr/lib64/R/library/slider/tests/testthat/_snaps/hop-vec.md
/usr/lib64/R/library/slider/tests/testthat/_snaps/hop.md
/usr/lib64/R/library/slider/tests/testthat/_snaps/hop2-vec.md
/usr/lib64/R/library/slider/tests/testthat/_snaps/phop-index-vec.md
/usr/lib64/R/library/slider/tests/testthat/_snaps/phop-index.md
/usr/lib64/R/library/slider/tests/testthat/_snaps/phop-vec.md
/usr/lib64/R/library/slider/tests/testthat/_snaps/phop.md
/usr/lib64/R/library/slider/tests/testthat/_snaps/pslide-index-vec.md
/usr/lib64/R/library/slider/tests/testthat/_snaps/pslide-index.md
/usr/lib64/R/library/slider/tests/testthat/_snaps/pslide-period-vec.md
/usr/lib64/R/library/slider/tests/testthat/_snaps/pslide-period.md
/usr/lib64/R/library/slider/tests/testthat/_snaps/pslide-vec.md
/usr/lib64/R/library/slider/tests/testthat/_snaps/pslide.md
/usr/lib64/R/library/slider/tests/testthat/_snaps/slide-index-vec.md
/usr/lib64/R/library/slider/tests/testthat/_snaps/slide-index.md
/usr/lib64/R/library/slider/tests/testthat/_snaps/slide-index2-vec.md
/usr/lib64/R/library/slider/tests/testthat/_snaps/slide-index2.md
/usr/lib64/R/library/slider/tests/testthat/_snaps/slide-period-vec.md
/usr/lib64/R/library/slider/tests/testthat/_snaps/slide-period.md
/usr/lib64/R/library/slider/tests/testthat/_snaps/slide-period2-vec.md
/usr/lib64/R/library/slider/tests/testthat/_snaps/slide-period2.md
/usr/lib64/R/library/slider/tests/testthat/_snaps/slide-vec.md
/usr/lib64/R/library/slider/tests/testthat/_snaps/slide.md
/usr/lib64/R/library/slider/tests/testthat/_snaps/slide2-vec.md
/usr/lib64/R/library/slider/tests/testthat/_snaps/slide2.md
/usr/lib64/R/library/slider/tests/testthat/_snaps/summary-index.md
/usr/lib64/R/library/slider/tests/testthat/_snaps/summary-slide.md
/usr/lib64/R/library/slider/tests/testthat/helper-date.R
/usr/lib64/R/library/slider/tests/testthat/helper-long-double.R
/usr/lib64/R/library/slider/tests/testthat/helper-s3.R
/usr/lib64/R/library/slider/tests/testthat/test-arithmetic.R
/usr/lib64/R/library/slider/tests/testthat/test-block.R
/usr/lib64/R/library/slider/tests/testthat/test-conditions.R
/usr/lib64/R/library/slider/tests/testthat/test-hop-index-vec.R
/usr/lib64/R/library/slider/tests/testthat/test-hop-index.R
/usr/lib64/R/library/slider/tests/testthat/test-hop-index2-vec.R
/usr/lib64/R/library/slider/tests/testthat/test-hop-index2.R
/usr/lib64/R/library/slider/tests/testthat/test-hop-vec.R
/usr/lib64/R/library/slider/tests/testthat/test-hop.R
/usr/lib64/R/library/slider/tests/testthat/test-hop2-vec.R
/usr/lib64/R/library/slider/tests/testthat/test-hop2.R
/usr/lib64/R/library/slider/tests/testthat/test-phop-index-vec.R
/usr/lib64/R/library/slider/tests/testthat/test-phop-index.R
/usr/lib64/R/library/slider/tests/testthat/test-phop-vec.R
/usr/lib64/R/library/slider/tests/testthat/test-phop.R
/usr/lib64/R/library/slider/tests/testthat/test-pslide-index-vec.R
/usr/lib64/R/library/slider/tests/testthat/test-pslide-index.R
/usr/lib64/R/library/slider/tests/testthat/test-pslide-period-vec.R
/usr/lib64/R/library/slider/tests/testthat/test-pslide-period.R
/usr/lib64/R/library/slider/tests/testthat/test-pslide-vec.R
/usr/lib64/R/library/slider/tests/testthat/test-pslide.R
/usr/lib64/R/library/slider/tests/testthat/test-slide-index-vec.R
/usr/lib64/R/library/slider/tests/testthat/test-slide-index.R
/usr/lib64/R/library/slider/tests/testthat/test-slide-index2-vec.R
/usr/lib64/R/library/slider/tests/testthat/test-slide-index2.R
/usr/lib64/R/library/slider/tests/testthat/test-slide-period-vec.R
/usr/lib64/R/library/slider/tests/testthat/test-slide-period.R
/usr/lib64/R/library/slider/tests/testthat/test-slide-period2-vec.R
/usr/lib64/R/library/slider/tests/testthat/test-slide-period2.R
/usr/lib64/R/library/slider/tests/testthat/test-slide-vec.R
/usr/lib64/R/library/slider/tests/testthat/test-slide.R
/usr/lib64/R/library/slider/tests/testthat/test-slide2-vec.R
/usr/lib64/R/library/slider/tests/testthat/test-slide2.R
/usr/lib64/R/library/slider/tests/testthat/test-summary-index.R
/usr/lib64/R/library/slider/tests/testthat/test-summary-slide.R
/usr/lib64/R/library/slider/tests/testthat/test-utils.R

%files lib
%defattr(-,root,root,-)
/usr/lib64/R/library/slider/libs/slider.so
/usr/lib64/R/library/slider/libs/slider.so.avx2
/usr/lib64/R/library/slider/libs/slider.so.avx512
